### ISSUE TITLE
Exception - Unnecessary validation in the new customer page (admin)

### ISSUE THREAD

**Issue by micso** [onepica/avatax#279]
### My versions
Magento: 1.13.0.1
Avatax: 3.7.0.0

### How to recreate a bug
Create a new customer in the admin panel (http://[YOURMAGENTOSITE]/admin/customer/new/)

### Error
`2018-09-18T13:12:39+00:00 ERR (3):
exception 'Mage_Core_Exception' with message 'The "" is not a valid customer code. Only latin letters, numbers and -._@ are allowed' in /app/Mage.php:594
Stack trace:
#0 /app/code/community/OnePica/AvaTaxAr2/Helper/Data.php(152): Mage::throwException('The "" is not a...')
#1 /app/code/community/OnePica/AvaTaxAr2/Helper/Data.php(128): OnePica_AvaTaxAr2_Helper_Data->validateCustomerCodeForHttpRequest(NULL)
#2 /app/code/community/OnePica/AvaTaxAr2/Helper/Data.php(75): OnePica_AvaTaxAr2_Helper_Data->generateCustomerNumber(Object(I95Dev_AdditionalContacts_Model_Customer))
#3 /app/code/community/OnePica/AvaTaxAr2/Block/Adminhtml/Customer/Documents/Grid.php(372): OnePica_AvaTaxAr2_Helper_Data->getCustomerNumberOrGenerate(Object(I95Dev_AdditionalContacts_Model_Customer))
#4 /app/code/community/OnePica/AvaTaxAr2/Block/Adminhtml/Customer/Documents/Grid.php(56): OnePica_AvaTaxAr2_Block_Adminhtml_Customer_Documents_Grid->_getCustomerNumberOrGenerate()
#5 /app/code/core/Mage/Core/Block/Abstract.php(265): OnePica_AvaTaxAr2_Block_Adminhtml_Customer_Documents_Grid->_prepareLayout()
#6 /app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#7 /app/code/community/OnePica/AvaTaxAr2/Block/Adminhtml/Customer/Documents.php(128): Mage_Core_Model_Layout->createBlock('avataxar2/admin...', 'documents.grid')
#8 /app/code/core/Mage/Core/Block/Abstract.php(265): OnePica_AvaTaxAr2_Block_Adminhtml_Customer_Documents->_prepareLayout()
#9 /app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#10 /app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(112): Mage_Core_Model_Layout->createBlock('avataxar2/admin...')
#11 [internal function]: Mage_Adminhtml_Block_Widget_Tabs->addTab('avataxar2_exemp...', 'avataxar2/admin...')
#12 /app/code/core/Mage/Core/Model/Layout.php(348): call_user_func_array(Array, Array)
#13 /app/code/core/Mage/Core/Model/Layout.php(214): Mage_Core_Model_Layout->_generateAction(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#14 /app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#15 /app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#16 /app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#17 /app/code/core/Mage/Adminhtml/Controller/Action.php(286): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#18 /app/code/core/Mage/Adminhtml/controllers/CustomerController.php(108): Mage_Adminhtml_Controller_Action->loadLayout()
#19 /app/code/core/Mage/Core/Controller/Varien/Action.php(424): Mage_Adminhtml_CustomerController->editAction()
#20 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch('edit')
#21 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#23 /app/Mage.php(683): Mage_Core_Model_App->run(Array)
#24 /index.php(92): Mage::run('lsc', 'store')
#25 {main}`

**Comment by marynychsv** [comment]
Greetings,

Please, open support ticket regarding Magento AvaTax connect via Avalara Support - support@avalara.com.
All requests should go through Avalara support and the respective ticket should be opened on Avalara side.

thank you,
